"""Added license table

Revision ID: ab57f3c60220
Revises: 4ceaba15382c
Create Date: 2024-09-01 01:52:16.262613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab57f3c60220'
down_revision: Union[str, None] = '4ceaba15382c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Не удаляем таблицы сразу
    # op.drop_table('licenses')
    pass
    # ### end Alembic commands ###
