"""Initial migration, created tables

Revision ID: 001
Revises:
Create Date: 2023-08-14 02:06:18.444546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registeredusers',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column(
        'registered_at',
        postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
        nullable=False
    ),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column(
        'created_at',
        postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
        nullable=False
    ),
    sa.Column('order_contents', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['registeredusers.telegram_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('registeredusers')
    # ### end Alembic commands ###