name: "advanced-tg-bots-testing-db"

services:
  db:
    image: postgres:16-alpine
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - "advanced-tg-bots-testing-db-postgres:/var/lib/postgresql/data"
    network_mode: host

volumes:
  advanced-tg-bots-testing-db-postgres: